baseURL = "https://valueguide.tech/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/


# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/templogo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "HI, This is 'VALUE GUIDE' and we do"
        description = "Weather you want to brain storm and your own mind map or explore completed mind maps, Sure'K is the way to go"
        btn     = true
        btnText = "Download More"
        btnURL  = ""
        [[params.banner.flipText]]
            title   = "Reliabiltiy Analytics"
        [[params.banner.flipText]]
            title   = "Maximize your plants Availabilty"
        [[params.banner.flipText]]
            title   = "Reliability Training"
        [[params.banner.flipText]]
            title   = "Risk Discovery"
        [[params.banner.flipText]]
            title   = "Risk Visualization"
            

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT US"
        content = "We are a Saudi company developing data analytics specifically for the manufacturing and whether you're looking for plant availability, reliability or safety improvement, Value Guide is the solution to unleash your data hidden value"
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Works"
        subtitle= "You ccan see samples of our work here"

    # Feature Product Section
    [params.featureProduct]
        enable  = true
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    
